apiVersion: v1
kind: Server
metadata:
    name: app-60
    comment: Python REST APIサーバー
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/setup.yaml
        inventory: playbook/hosts.yaml
    networkInterface:
        - networkname: host-bridge
