#user_name :       "ubuntu"
#flannel_version : "v0.12.0"
#cpu_arch  :       "amd64"
#download_dir :    "/tmp"
#ca_kubeconfig:    "/tmp"
#cni_plugins :     "v1.6.0"
#cadmin_home :     "/home/ubuntu"
#cluster_admin :   "ubuntu"
#iface_pri:        "enp1s0"