apiVersion: v1
kind: Gateway
metadata:
    name: lb-gw
spec:
    bindPublicIpAddress: 192.168.1.48    # パブリック側のIPアドレスでアクセスを許可
    internalServerName: lb1              # サーバーの名前
    internalVirtualNetwork: webs-net     # 内部側の仮想ネットワーク
    serverPorts:                         # リクエストを転送するポート番号のリストを以下に記述する
        - http
        - https