apiVersion: v1
kind: Server
metadata:
    name: webserver-1
    labels:
      lb-enabled: "true"
    comment: Webサーバー#1
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: webs-net
        - networkname: default