apiVersion: v1
kind: KubernetesEngine
metadata:
    name: mke0
    comment: 検証用K8sクラスタ
spec:
    version: "1.36"
    nodes: 3
    nodeSpec:
        cpu: 2
        memory: 4192
        auth:
            url: https://github.com/takara9.keys
