---
apiVersion: v1
kind: VirtualNetwork
metadata:
  name: db-net
  comment: DBサーバー用の仮想ネットワーク
spec:
  iPNetworkAddress: 172.16.90.0/24
---
apiVersion: v1
kind: VirtualNetwork
metadata:
  name: rest-net
  comment: RESTサーバー用の仮想ネットワーク
spec:
  iPNetworkAddress: 172.16.100.0/24
---
apiVersion: v1
kind: VirtualNetwork
metadata:
  name: biz-net
  comment: 業務サーバー用の仮想ネットワーク
spec:
  iPNetworkAddress: 172.16.120.0/24
