apiVersion: v1
kind: ApplicationLoadBalancer
metadata:
    name: alb-web
spec:
    bindPublicIpAddress: 192.168.1.70
    internalVirtualNetwork: app-net
    listeners:
        - name: web-http
          protocol: HTTP
          vipPort: 80
          backendPort: 80
          backendSelector:
              matchLabels:
                  app: web
          loadBalancingAlgorithm: roundrobin
          healthCheck:
              enabled: true
          sessionPersistence:
              enabled: false
