apiVersion: v1
kind: Server
metadata:
    name: srv05-1
    comment: プライベートネットワークに接続するサーバー
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6CPvNHHeF8rHScC7vrq7HMqTPQJcl08atMSqHk/gSy For marmot VMs"
        users:
         - ubuntu
    networkInterface:
        - networkname: net-admin
---
apiVersion: v1
kind: Server
metadata:
    name: srv05-2
    comment: プライベートネットワークに接続するサーバー
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6CPvNHHeF8rHScC7vrq7HMqTPQJcl08atMSqHk/gSy For marmot VMs"
        users:
         - ubuntu
    networkInterface:
        - networkname: net-admin
