apiVersion: v1
kind: ApplicationLoadBalancer
metadata:
    name: alb-web
spec:
    bindPublicIpAddress: 10.10.0.70
    routes:
    - to: default
      via: 10.10.0.1
    internalVirtualNetwork: app-net
    listeners:
        - name: web-http
          protocol: HTTP
          vipPort: 80
          backendPort: 80
          backendSelector:
              matchLabels:
                  app: web3
          loadBalancingAlgorithm: roundrobin
          healthCheck:
              enabled: false
          sessionPersistence:
              enabled: true
