apiVersion: v1
kind: Server
metadata:
    name: web-1
    comment: プライベートネットワークに接続するサーバー
    labels:
        app: web3
spec:
    cpu: 1
    memory: 1024
    mmImage: webserver1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: app-net
        - networkname: default
        - networkname: host-bridge
---
apiVersion: v1
kind: Server
metadata:
    name: web-2
    comment: プライベートネットワークに接続するサーバー
    labels:
        app: web3
spec:
    cpu: 1
    memory: 1024
    mmImage: webserver1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: app-net
        - networkname: default
---
apiVersion: v1
kind: Server
metadata:
    name: web-3
    comment: プライベートネットワークに接続するサーバー
    labels:
        app: web3
spec:
    cpu: 1
    memory: 1024
    mmImage: webserver1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: app-net
        - networkname: default
