apiVersion: v1
kind: Server
metadata:
    name: server-120
    #nodeName: marmot3
    comment: 事前定義済のボリュームを名前で指定する例
spec:
    cpu: 2
    memory: 2048
    mmImage: ubuntu24.04
    storage:
        - metadata:
            name: vol-iscsi-1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
