##
## Install Prometheus Oprator
##
- name: check kube-prometheus
  stat:
    path: "{{ temp_dir }}/kube-prometheus/README.md"
  register: regi_prometheus

- name: git clone kube-prometheus
  become_user: "{{ cluster_admin }}"
  git:
    repo: 'https://github.com/prometheus-operator/kube-prometheus'
    version: release-0.18
    dest: "{{ temp_dir }}/kube-prometheus"
  when: regi_prometheus.stat.exists == False

- name: deploy kube-prometheus-1
  become_user: "{{ cluster_admin }}"
  shell: |
        kubectl apply --server-side -f manifests/setup
  args:
    chdir: "{{ temp_dir }}/kube-prometheus"

- name: deploy kube-prometheus-2
  become_user: "{{ cluster_admin }}"
  shell: |
        kubectl wait \
            --for condition=Established \
            --all CustomResourceDefinition \
            --namespace=monitoring
  args:
    chdir: "{{ temp_dir }}/kube-prometheus"

- name: deploy kube-prometheus-3
  become_user: "{{ cluster_admin }}"
  shell: |
        kubectl apply -f manifests/
  args:
    chdir: "{{ temp_dir }}/kube-prometheus"


  
