apiVersion: v1
kind: Volume
metadata:
    name: lvm-vol1
spec:
    type: lvm
    size: 5
    persistent: true
---
apiVersion: v1
kind: Server
metadata:
    name: server-43
    comment: LVMボリュームを使用するサーバー
spec:
    cpu: 1
    memory: 1048
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
          address: 10.10.0.43
          netmasklen: 24
          routes:
            - to: default
              via: 10.10.0.1
          nameservers:
            addresses:
                - 8.8.8.8
            search:
                - labo.local
    storage:
        # 事前定義済のボリュームを名前で指定する例
        - metadata:
            name: lvm-vol1