apiVersion: v1
kind: Server
metadata:
    name: server-41
    comment: Ansibleプレイブックを自動実行するサーバー
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        onBoot: true
        remotePlaybook: https://github.com/takara9/marmot-manifests/blob/main/50-setup-ansible/playbook/setup.yaml
    networkInterface:
        - networkname: default
