apiVersion: v1
kind: Server
metadata:
    name: server-111
    comment: Ansibleで、dockerコマンドをインストールするサーバー
spec:
    cpu: 2
    memory: 2028
    osVariant: docker
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.111
          netmasklen: 24
          nameservers:
            addresses:
                - 192.168.1.9
            search:
                - labo.local
          routes:
            - to: default
              via: 192.168.1.1
