- name: "kubeのコンフィグディレクトリ作成"
  file:
    path:  "/home/{{ cluster_admin }}/.kube"
    state: directory
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0755'

- name: "kubeのコンフィグをホームディレクトリにコピー"
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/home/{{ cluster_admin }}/.kube/config"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'

- name: "共有ディレクトリにadmin.confをコピー"
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "/mnt/admin.kubeconfig_{{ cluster_name }}"
    remote_src: yes
    owner: "{{ cluster_admin }}"
    group: "{{ cluster_admin }}"
    mode:  '0600'

