- debug: msg="{{ ansible_facts }}"
- name: "kubeadm-config.yamlの作成"
  template:
    src: "kubeadm-config.yaml"
    dest: "/etc/kubernetes/kubeadm-config.yaml"
    owner: root
    group: root
    mode:  '0644'

# kubeadm-config.yaml の中で、サブネットの指定があるので、ここで指定した値をテンプレートに渡す必要があります。
- name: "kubeadmの初期化"
  shell: |
     kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  args:
    chdir: "{{ nfs_share_dir }}"
  register: kubeadm_shell_output

- debug: msg="{{ kubeadm_shell_output.stdout_lines}}"
- debug: msg="{{ kubeadm_shell_output.stdout_lines[-2]}}"
- debug: msg="{{ kubeadm_shell_output.stdout_lines[-1]}}"

- name: "kubeのコンフィグ取得"
  include_tasks: kubeconfig_setup.yml

- name: Delete kubeadm_join.sh
  file:
    path: "{{ nfs_share_dir }}/kubeadm_join_{{ cluster_name }}.sh"
    state: absent

- template:
    src: join.sh.j2
    dest: "{{ nfs_share_dir }}/kubeadm_join_{{ cluster_name }}.sh"
    owner: root
    group: root
    mode: '0755'

