- name: "Linuxのセットアップとコンテナランタイムのインストール"
  hosts: all
  gather_facts: true
  become: true
  roles:
    - setup-linux
    - containerd
    - kubeadm


- name: "NFSサーバーの設定"
  hosts: master
  become: true
  vars:
    nfs_export_dir: "/mnt"
    nfs_allowed_client: "192.168.1.0/24"
  roles:
    - nfs-server


- name: "NFSクライアントの設定"
  hosts: nodes
  become: true
  vars:
    nfs_server_ip: "192.168.1.220"
    nfs_server_dir: "/mnt"
    nfs_mount_point: "/mnt"
  roles:
    - nfs-client

- name: "コントロールプレーンのインストール"
  hosts: master
  gather_facts: true
  become: true
  roles:
    - master

- name: "ワーカーノードの参加"
  hosts: nodes
  become: true
  roles:
    - worker

- name: "ネットワークプラグインのインストール"
  hosts: master
  gather_facts: true
  become: true
  roles:
    # net-cilium
    - net-flannel
- name: "kube設定ディレクトリの回収"
  hosts: master 
  tasks:
    - name: .kube ディレクトリをローカルにコピー
      ansible.posix.synchronize:
        mode: pull
        src: "/home/ubuntu/.kube/"
        dest: "~/.kube/"  # ローカルの保存先（カレントディレクトリ配下）