#ubuntu@master:~$ apt-cache madison kubeadm
#   kubeadm | 1.36.2-2.1 | https://pkgs.k8s.io/core:/stable:/v1.36/deb  Packages
#   kubeadm | 1.36.1-1.1 | https://pkgs.k8s.io/core:/stable:/v1.36/deb  Packages
#   kubeadm | 1.36.0-1.1 | https://pkgs.k8s.io/core:/stable:/v1.36/deb  Packages

#k8s_version: "v1.36"
#k8s_package_version: "1.36.2-2.1"