# kubeadm-config.yaml
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
localAPIEndpoint:
  advertiseAddress: "192.168.1.220"
  bindPort: 6443
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: "{{ kubernetes_version }}"
networking:
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "{{ pod_cidr }}"
  dnsDomain: "cluster.local"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
