apiVersion: v1
kind: Server
metadata:
    name: server-1
    comment: 仮想サーバーのCPUの増減テスト用
spec:
    cpu: 2
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
