apiVersion: v1
kind: Server
metadata:
    name: server-1
    comment: 仮想サーバーのコメントの変更
    labels:
        env: test
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.20
          netmasklen: 24
          routes:
            - to: default
              via: 192.168.1.1
          nameservers:
            addresses:
                - 192.168.1.9
            search:
                - labo.local
