apiVersion: v1
kind: Server
metadata:
    name: server-109
    comment: 事前定義済のボリュームを名前で指定する例
spec:
    cpu: 2
    memory: 2048
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    storage:
        # 事前定義済のボリュームを名前で指定する例
        - metadata:
            name: volume2
    networkInterface:
        - networkname: host-bridge
          address: 10.10.0.109
          netmasklen: 24
          routes:
            - to: default
              via: 10.10.0.1
          nameservers:
            addresses:
                - 8.8.8.8
            search:
                - labo.local
