apiVersion: v1
kind: NetworkLoadBalancer
metadata:
    name: nlb1
spec:
    bindPublicIpAddress: 10.10.0.72
    remoteCIDR: 10.10.0.0/24
    internalVirtualNetwork: nlb-net
    listeners:
        - name: http
          protocol: tcp
          vipPort: 80
          backendPort: 80
          backendSelector:
              matchLabels:
                  app: web
