apiVersion: v1
kind: Server
metadata:
    name: webserver1
    comment: プライベートネットワークに接続するサーバー
    labels:
        app: web
spec:
    cpu: 1
    memory: 1024
    mmImage: webserver1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: nlb-net
        - networkname: default
---
apiVersion: v1
kind: Server
metadata:
    name: webserver2
    comment: プライベートネットワークに接続するサーバー
    labels:
        app: web
spec:
    cpu: 1
    memory: 1024
    mmImage: webserver1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: nlb-net
        - networkname: default
---
apiVersion: v1
kind: Server
metadata:
    name: webserver3
    comment: プライベートネットワークに接続するサーバー
    labels:
        app: web
spec:
    cpu: 1
    memory: 1024
    mmImage: webserver1
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: nlb-net
        - networkname: default
