apiVersion: v1
kind: Server
metadata:
    name: ceph-client1
    comment: シングル最小構成のCeph client
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu22.04 # download.ceph.com の debian-tentacle(jammy)リポジトリで最新版を使用
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/install-client.yaml
        inventory: playbook/hosts-client1.yaml
    networkInterface:
        - networkname: host-bridge
