# CephFS(ファイルストレージ)用の Ceph-CSI 認証情報
# userID/userKey には "client." を除いたユーザー名と、そのキーを指定する
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: default
stringData:
  userID: admin
  userKey: AQDJZYFqTvwQNhAA6x7tfYVJ04CyoKrn8qcVOg==
