apiVersion: v1
kind: Server
metadata:
    name: server-110
    comment: Ansibleで、dockerコマンドをインストールするサーバー
spec:
    cpu: 2
    memory: 2048
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/install.yaml
        inventory: hosts.yaml
    networkInterface:
        - networkname: host-bridge
          address: 10.10.0.110
          netmasklen: 24
          routes:
            - to: default
              via: 10.10.0.1
          nameservers:
            addresses:
                - 8.8.8.8
            search:
                - labo.local
