apiVersion: v1
kind: Server
metadata:
    name: server-01
    comment: デフォルトネットワークに繋がる設定
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    networkInterface:
        - networkname: default
