apiVersion: v1
kind: Server
metadata:
    name: server-42
    comment: サーバー作成時にボリューム作成するサーバー
spec:
    cpu: 1
    memory: 1048
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.42
          netmasklen: 24
          routes:
            - to: default
              via: 192.168.1.1
          nameservers:
            addresses:
                - 192.168.1.9
            search:
                - labo.local
    storage:
        - metadata:
            name: var
            comment: runnerの作業エリアとして利用
          spec:
            size: 2
        - metadata:
            name: for-vg1
            comment: OSディスク用のボリュームグループ用のボリューム
          spec:
            size: 1
        - metadata:
            name: for-vg2
            comment: DATAディスク用のボリュームグループ用のボリューム
          spec:
            size: 1
            persistent: true
