apiVersion: v1
kind: Server
metadata:
    name: server-60
    comment: プライベートネットワークに接続するサーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: private-webs
        - networkname: default
        - networkname: host-bridge
          address: 192.168.1.63
          nameservers:
            addresses:
                - 192.168.1.9
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
                - lab.local
          netmasklen: 24
          routes:
            - to: default
              via: 192.168.1.1
