apiVersion: v1
kind: Server
metadata:
    name: server-45
    comment: Cpehボリュームを使用するサーバー
spec:
    cpu: 1
    memory: 1048
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
    storage:
        # 事前定義済のボリュームを名前で指定する例
        - metadata:
            name: vol-45
