apiVersion: v1
kind: Server
metadata:
    name: server-92
    comment: GitHubに登録した公開鍵でSSHログインできるサーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
        users:
            - ubuntu
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.92
          netmasklen: 24
          routes:
            - to: default
              via: 192.168.1.1
          nameservers:
            addresses:
                - 192.168.1.9
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
