apiVersion: v1
kind: Pod
metadata:
  name: alpine
  labels:
    app: ubuntu
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
