apiVersion: v1
kind: Pod
metadata:
  name: pod-u3
  labels:
    app: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:24.04
    command: ["sleep", "infinity"]
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
