apiVersion: v1
kind: Image
metadata:
    name: rocky9
spec:
    sourceUrl: https://download.rockylinux.org/pub/rocky/9/images/x86_64/Rocky-9-GenericCloud.latest.x86_64.qcow2
    osName: rocky
    osVersion: "9"
