apiVersion: v1
kind: Image
metadata:
    name: almalinux9
spec:
    sourceUrl: "https://repo.almalinux.org/almalinux/9/cloud/x86_64/images/AlmaLinux-9-GenericCloud-latest.x86_64.qcow2"
    osName: almalinux
    osVersion: "9"
