apiVersion: v1
kind: Image
metadata:
    name: rocky8
spec:
    sourceUrl: "https://dl.rockylinux.org/pub/rocky/8/images/x86_64/Rocky-8-GenericCloud.latest.x86_64.qcow2"   
    osName: "rocky"
    osVersion: "8"
