apiVersion: v1
kind: Server
metadata:
    name: ubuntu24-52
    comment: marmotホストが繋がるネットワークに接続する仮想サーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
          address: 10.10.0.52
          netmasklen: 24
          routes:
            - to: default
              via: 10.10.0.1
          nameservers:
            addresses:
                - 8.8.8.8
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
