apiVersion: v1
kind: Server
metadata:
    name: alpine51
    comment: marmotホストが繋がるネットワークに接続する仮想サーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: alpine3
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.51
          netmasklen: 24
          routes:
            - to: default
              via: 192.168.1.1
          nameservers:
            addresses:
                - 192.168.1.9
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
