apiVersion: v1
kind: Server
metadata:
    name: srv-almalinux9
    comment: marmotホストが繋がるネットワークに接続する仮想サーバー
    labels:
        unit: 22
        role: almalinux
spec:
    cpu: 1
    memory: 1024
    mmImage: almalinux9
    auth:
        publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6CPvNHHeF8rHScC7vrq7HMqTPQJcl08atMSqHk/gSy For marmot VMs"
    networkInterface:
        - networkname: host-bridge
