apiVersion: v1
kind: Server
metadata:
    name: server-91
    comment: ローカル環境で作成した鍵ペアでSSHログインできるサーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFOSkHRgel695I/R+TEyfCr98IcoBJtTyFLrNpb7V331 For marmot VMs"
        users:
         - ubuntu
    networkInterface:
        - networkname: host-bridge
          address: 10.10.0.91
          netmasklen: 24
          routes:
            - to: default
              via: 10.10.0.1
          nameservers:
            addresses:
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
