apiVersion: v1
kind: VpnGateway
metadata:
    name: vpn-gw
spec:
    bindPublicIpAddress: 10.10.0.40 # VPN-GWのエンドポイント
    internalVirtualNetwork: admin     # 内部側の仮想ネットワーク
    remoteCIDRs:                      # アクセスを受け付けるアドレス
      - 10.10.0.0/24                  

