apiVersion: v1
kind: Server
metadata:
    name: server-41
    comment: Ansibleプレイブックを自動実行するサーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/setup.yaml
        inventory: hosts.yaml
        extra-args:
            - flush-cache
            - tags "nginx,mysql"
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.41
          netmasklen: 24
          nameservers:
            addresses:
                - 192.168.1.9
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
                - lab.local
          routes:
            - to: default
              via: 192.168.1.1
