apiVersion: v1
kind: Server
metadata:
    name: rest3
    comment: 5桁乱数文字列 REST API サービス
spec:
    cpu: 1
    memory: 2048
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/rest-svc-3-setup.yaml
        inventory: playbook/hosts.yaml
    networkInterface:
        - networkname: host-bridge
        - networkname: rest-net
