apiVersion: v1
kind: Server
metadata:
    name: rest-svc-1 
    comment: Python REST APIサーバー
spec:
    cpu: 1
    memory: 2048
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/rest-svc-1-setup.yaml
        inventory: playbook/hosts.yaml
    networkInterface:
        - networkname: host-bridge
        - networkname: db-net
        - networkname: rest-net

 
