apiVersion: v1
kind: NetworkLoadBalancer
metadata:
    name: nlb1
spec:
    bindPublicIpAddress: 192.168.1.72
    remoteCIDR: 192.168.0.0/16
    internalVirtualNetwork: nlb-net
    listeners:
        - name: http
          protocol: tcp
          vipPort: 80
          backendPort: 3000
          backendSelector:
              matchLabels:
                  app: web
