apiVersion: v1
kind: Server
metadata:
    name: server-80
    comment: rootパスワードでSSHログインできるサーバー （非推奨）
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        rootPassword: password123
    networkInterface:
        - networkname: host-bridge
