apiVersion: v1
kind: Server
metadata:
    name: server-90
    comment: rootパスワードでSSHログインできるサーバー （非推奨）
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        rootPassword: password123
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.90
          netmasklen: 24
          routes:
            - to: default
              via: 192.168.1.1
          nameservers:
            addresses:
                - 192.168.1.9
                - 8.8.8.8
                - 8.8.4.4
            search:
                - labo.local
