- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - bridge-utils

