apiVersion: v1
kind: ApplicationLoadBalancer
metadata:
    name: alb-web
    comment: Webサーバー用のアプリケーションロードバランサ
    labels:
        case: 30
        role: web
spec:
    bindPublicIpAddress: 192.168.1.180
    routes:
    - to: default
      via: 192.168.1.1
    internalVirtualNetwork: pri-net-web
    listeners:
        - name: web-http
          protocol: HTTP
          vipPort: 80
          backendPort: 3000
          backendSelector:
              matchLabels:
                  role: web
          loadBalancingAlgorithm: roundrobin
          healthCheck:
              enabled: false
          sessionPersistence:
              enabled: true
