apiVersion: v1
kind: ApplicationLoadBalancer
metadata:
    name: alb30
    comment: Webサーバー用のアプリケーションロードバランサ
    labels:
        case: 30
        role: web
spec:
    bindPublicIpAddress: 192.168.1.180
    routes:
    - to: default
      via: 192.168.1.1
    internalVirtualNetwork: pri-net-web
    listeners:
        - name: web-http
          protocol: HTTP
          vipPort: 80
          backendPort: 3000
          backendSelector:
              matchLabels:
                  role: web
          loadBalancingAlgorithm: roundrobin
          healthCheck:
              enabled: false
          sessionPersistence:
              enabled: true
---
apiVersion: v1
kind: Gateway
metadata:
    name: gw30
    comment: Privateネットワークのゲートウェイ
    labels:
        case: 30
        role: gateway
spec:
    bindPublicIpAddress: 192.168.1.181      # パブリック側のIPアドレスでアクセスを許可
    internalServerName: srv30-bastion       # サーバーの名前
    internalVirtualNetwork: pri-net-bastion # 内部側の仮想ネットワーク
    remoteCIDR: 0.0.0.0/0                   # 接続を許すリモートのIPアドレス
    serverPorts:                            # リクエストを転送するポート番号のリストを以下に記述する
        - ssh                               # sshとhttpの通信を許可、それ以外は禁止    
        - http
