apiVersion: v1
kind: VirtualNetwork
metadata:
  name: pri-net-bastion
  comment: 踏み台サーバー用のプライベートネットのネットワーク
  labels:
      case: 30
      role: bastion
spec:
  iPNetworkAddress: 172.16.90.0/26
---
apiVersion: v1
kind: VirtualNetwork
metadata:
  name: pri-net-web
  comment: Webサーバー用のプライベートネットのネットワーク
  labels:
      case: 30
      role: web
spec:
  iPNetworkAddress: 10.120.1.0/24
---
apiVersion: v1
kind: VirtualNetwork
metadata:
  name: pri-net-db
  comment: DBサーバー用のプライベートネットのネットワーク
  labels:
      case: 30
      role: db
spec:
  iPNetworkAddress: 10.120.10.0/24
