apiVersion: v1
kind: Server
metadata:
    name: server-32
    comment: プライベートネットワークに接続するサーバー
spec:
    cpu: 1
    memory: 1024
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    networkInterface:
        - networkname: private
        - networkname: default
