apiVersion: v1
kind: Server
metadata:
    name: webphp
    comment: Ansibleで、Web-php-serverをインストールする
    labels:
        app: webphp
spec:
    cpu: 2
    memory: 2048
    osVariant: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/install.yaml
        inventory: playbook/hosts.yaml
    networkInterface:
        - networkname: host-bridge
          address: 192.168.1.91
          netmasklen: 24
          nameservers:
            addresses:
                - 192.168.1.9
            search:
                - labo.local
          routes:
            - to: default
              via: 192.168.1.1
