apiVersion: v1
kind: Server
metadata:
    name: webphp
    comment: Ansibleで、Web-php-serverをインストールする
    labels:
        app: webphp
        num: 55
spec:
    cpu: 2
    memory: 2048
    mmImage: ubuntu24.04
    auth:
        url: https://github.com/takara9.keys
    ansible:
        playbook: playbook/install.yaml
        inventory: playbook/hosts.yaml
    networkInterface:
        - networkname: host-bridge
          address: 10.10.0.81
          netmasklen: 24
          nameservers:
            addresses:
                - 8.8.8.8
            search:
                - labo.local
          routes:
            - to: default
              via: 10.10.0.1
