apiVersion: v1
kind: Server
metadata:
    name: srv-dhcp6
    comment: DHCPクライアントとして動作する仮想サーバー
spec:
    cpu: 1
    memory: 1024
    mmImage: ubuntu24.04
    auth:
        publicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP6CPvNHHeF8rHScC7vrq7HMqTPQJcl08atMSqHk/gSy For marmot VMs"
        users:
         - ubuntu        
    networkInterface:
        - networkname: host-bridge
          dhcp4: false
          dhcp6: true
