all:
  vars:
    common_connection: &common_connection
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
      marmotd_server_ip: 10.1.0.11

    common_rest_api_mysql: &common_rest_api_mysql
      rest_api_mysql_host: "db.db-net"
      rest_api_mysql_port: 3306
      rest_api_mysql_user: "mysqladmin"
      rest_api_mysql_password: "komekomekome"
      rest_api_mysql_database: "bomdb"
      rest_api_mysql_connect_timeout: 15

    common_rest_api_upstream: &common_rest_api_upstream
      rest_api_random_digits_api_url: "http://rest3.rest-net:5000/random-5digits"
      rest_api_bom_tree_api_url: "http://rest2.rest-net:5000/bom-tree"
      rest_api_bom_tree_api_urls:
        - "http://rest1.rest-net:5000/bom-tree"
        - "http://rest2.rest-net:5000/bom-tree"
      rest_api_upstream_timeout: 15
      rest_api_bom_tree_retry_limit: 20

  hosts:
    biz:
      <<: [*common_connection, *common_rest_api_mysql, *common_rest_api_upstream]
      ansible_host: biz

    db:
      <<: *common_connection
      ansible_host: db

    rest1:
      <<: [*common_connection, *common_rest_api_mysql]
      ansible_host: rest1

    rest2:
      <<: [*common_connection, *common_rest_api_mysql]
      ansible_host: rest2
      rest_api_response_delay_seconds: 0

    rest3:
      <<: *common_connection
      ansible_host: rest3