- name: systemd-resolvedの停止と無効化
  systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: no

- name: resolv.confの設定
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
